### ISSUE TITLE
Please update to the latest version

### ISSUE THREAD

**Issue by CocoaBob** [gregispitzer/kedei_3.5inch_dirver_v6_1_3#1]
Hi,

I tried your version, it simply shows a blank screen after rebooting, seems it's not compatible with the latest Raspbian any more.

I finally downloaded the official one from here http://kedei.net/raspberry/raspberry.html, and then it works very well.

Now I uploaded it to my Droplr drive here: https://d.pr/f/kh5JbR

Hope it could help someone out there.

Best,

**Comment by gregispitzer** [comment]
I downloaded and updated the file today. Thx for the info
